### ISSUE TITLE
Rename custom-conf folder to custom-sites

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#188]
For some sites, we need to provide additional images that are displayed on the web (logo, icons). For that reason, we will rename the `custom-conf` folder as `custom-sites`, and change the structure of this folder as follow:

```
custom-sites/
├── site1/
│   └──  iva/
│       ├── conf/
│       └── img/
├── site2/
│   └──  iva/
│       ├── conf/
│       └── img/
. . .
```

Also, we will rename the command `npm run build --custom-config=site1` as  `npm run build --custom-site=site1`.

**Comment by Rodielm** [comment]
When a `custom-site` is provided, the server cannot find the resource because it's looking the resource in the file path from index. So for the solution, we configured the server if we apply the `custom-site`, it will take the resources from this `custom-site`, that way we can avoid the missing resources.
