### ISSUE TITLE
Improve saved filters dropdown

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#207]
There are some filters that are not saved in the server, so the delete button does nothing: 

![image](https://user-images.githubusercontent.com/5751201/138672525-da1718eb-e928-4be6-94f6-152299655d0c.png)

Also, saved filters are displayed in the same group with the filters defined in the configuration: 

![image](https://user-images.githubusercontent.com/5751201/138672813-c34941d1-26f4-4f5f-8c5c-fd036c60a8af.png)

Tasks:
- [x] Disable deleting filters that are not saved in the server (default and customized in the config).
- [x] Improve filters groups: display saved filters in another group.

**Comment by lebinh190998** [comment]
Hi there, I'd like to work on this task, but I have no accounts to login. Where can I get it?

**Comment by halender** [comment]
Related to #336 . Moved to 2.3 milestone.

**Comment by imedina** [comment]
@lebinh190998 sorry so much for not getting back to you! :-(  I just did not see it until few days ago
Thank you so much for the offer, more than happy to get help! :-)

**Comment by imedina** [comment]
I have just made a simple fix, now delete icon is displayed properly and I have added a header:

![image](https://user-images.githubusercontent.com/1427327/152470053-a7003572-c9c3-4cfc-8990-654847ec65ef.png)

**Comment by pamag** [comment]
## Reviewed

commit 122f092ad6c7d1ddaec064ff5eaac7fb291b4095

FIXED with ISSUES @imedina @jmjuanes 

- [ ] after creating a filter it appears in the dropdown but does not have the delete icon
122f092ad6c7d1ddaec064ff5eaac7fb291b4095

- [ ] When a filter is deleted it does not disappear from the dropdown and if you try to delete again it raises an error
