### ISSUE TITLE
case interpreter->variant browser-> consequence type filter drop down selection has odd behaviour

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#246]
## Description
In the "Consequence Type" filter of the "variant browser", The "Custom consequence type selection" drop-down scrolling is not working properly:

![Peek 2021-11-09 02-30](https://user-images.githubusercontent.com/167875/140845515-c7e198bc-fcb6-45a2-8953-d1fb9a229f23.gif)

**Comment by jmjuanes** [comment]
Fixed in commit 49d49e1: added property to `select-field-filter` component to specify a fixed dropdown height: 


![image](https://user-images.githubusercontent.com/5751201/142000899-8f35d29d-21a9-419d-a37f-b0ff508688b4.png)

References: 
- https://developer.snapappointments.com/bootstrap-select/options/#core-options
- https://stackoverflow.com/a/39630641

**Comment by pamag** [comment]
## Reviewed
OK
