### ISSUE TITLE
Fix new notifications display

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#292]
## Describe bug

The new notification has a rendering issue in some situations. The text displayed is rendered outside the notification area.

Before:
![image](https://user-images.githubusercontent.com/167875/146686861-f4294509-79c9-47ea-9e32-76d2542b1095.png)

Current:
![image](https://user-images.githubusercontent.com/167875/146686873-36374f99-f4c8-4f5d-afc5-615c2aaf8adb.png)

For an example, you can see issue https://github.com/opencb/jsorolla/issues/244

**Comment by jmjuanes** [comment]
Can not replicate the same error as described in issue #244, but got a new error message: 

![image](https://user-images.githubusercontent.com/5751201/146796770-99f019f7-5ec9-4843-a3d3-663df25592d5.png)

**Comment by pamag** [comment]
> Can not replicate the same error as described in issue #244, but got a new error message:
> 
> ![image](https://user-images.githubusercontent.com/5751201/146796770-99f019f7-5ec9-4843-a3d3-663df25592d5.png)

have you tried with this commti https://github.com/opencb/jsorolla/commit/b7e64ae9643b3d8a5f404e6d456c8599cc410cd5 to reproduce the same long message?

**Comment by jmjuanes** [comment]
Replicated with a lorem ipsum text: 

![image](https://user-images.githubusercontent.com/5751201/146927955-82b1e0c7-52a7-4cab-bb8a-256488700771.png)

**Comment by jmjuanes** [comment]
Fixed in commit eae470b:

- Applied `word-break: break-all;` to the message `<div>` container to prevent text overflow (see https://developer.mozilla.org/en-US/docs/Web/CSS/word-break). 

![image](https://user-images.githubusercontent.com/5751201/146929525-218abfe0-8366-4cab-949c-3059e620bc11.png)

- Added `max-height` property to the message container to limit the maximum height of the displayed text. This value can be provided in the manager configuration, using the `messageMaxHeight` field. The default value is `200px`.

![image](https://user-images.githubusercontent.com/5751201/146929394-a6946b65-32cc-4380-895d-7b9a122a5202.png)

**Comment by pamag** [comment]
## Reviewed

FIXED
