### ISSUE TITLE
Clear interpretation error

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#308]
## Describe the bug

commit 4f8dbe4c2eedc15edf987bc30eaa8f52a851b939

Error when clearing an interpretation

```
CatalogException
More than one study found. Please, be more specific. The accepted pattern is [ownerId@projectId:studyId]
```
![clear_interpretatin_error](https://user-images.githubusercontent.com/167875/147174265-0dad7d98-ece7-4f67-b157-b33ef7968043.gif)

**Comment by jmjuanes** [comment]
The problem is that the OpenCGA client is sending the `study` value as the `body` instead of setting it as a param-query: 

![image](https://user-images.githubusercontent.com/5751201/149187481-1b0ea9bd-e980-4c16-81b7-dc13f1ceefbd.png)

![image](https://user-images.githubusercontent.com/5751201/149187575-63ef8241-6552-4f17-b984-6fab659d1f41.png)

**Comment by pamag** [comment]
## Reviewed
commit: 14e000be3b396e4a1f6f8849d2fc425130d6749d

Fixed
