### ISSUE TITLE
VB detailed sample tab: column sex issue when no karyotypic sex

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#327]
## Describe the bug

When a sample has karyotypic sex unknown

![image](https://user-images.githubusercontent.com/167875/148149014-41961725-94c7-4dfa-a42b-ae2aff1476a5.png)

In the VB detailed tabs, the sample tab has an error in the column SEX

![image](https://user-images.githubusercontent.com/167875/148148884-448d0eb1-c531-4e77-bf31-414a343ae864.png)

**Comment by jmjuanes** [comment]
Fixed in commit 3b3d632. The field `sex` is an object, so that is the reason that the column displays `[object Object]`. Displaying now `sex.id` instead: 

https://github.com/opencb/jsorolla/blob/3b3d632d24c4f693b4dcf2adb2e795b791ddde9b/src/webcomponents/variant/variant-samples.js#L110-L112

![image](https://user-images.githubusercontent.com/5751201/148209544-ebe016e1-8c86-47e6-a85f-8cf83395836d.png)

**Comment by pamag** [comment]
## Reviewed

Fixed but makes IVA backward-incompatible with OpenCGA where `sex` and `ethnicity` are strings (<2.2.0)
