### ISSUE TITLE
Selecting default_initial_query in FILTERS menu does not remove the depth_filter label

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#352]
## Describe the bug

The action "default_initial_query" does not clear the filter for "depth":

![image](https://user-images.githubusercontent.com/167875/149850147-dd933675-49d8-46a4-b816-5bad8d20a088.png)

it moves the filter label to the second position:

![image](https://user-images.githubusercontent.com/167875/149850161-55427009-8680-45c8-aba5-80bf29778154.png)

## How to reproduce

![depth_filter_not_removed_with_default](https://user-images.githubusercontent.com/167875/149850069-947709e3-da89-4b0d-8901-d28b9e93e364.gif)

**Comment by Rodielm** [comment]
The reason why the `depth` is not removed when running the `initial query` is because of this config in the `opencga-active-filter`.  Especially `sampleData`

The real problem is that if we remove it, this could affect other components that use `opencga-active-filter`.
![image](https://user-images.githubusercontent.com/10471758/151551403-9da1fb03-5355-4d9a-9c6b-b644bdac68f8.png)

This issue will be discussed later on how to solve it without affecting other components.

**Comment by pamag** [comment]
## Reviewed
commit: 8d57f06f56a759e4b142e515e32659ff15b5e597

FIXED
